---
title: "Wine Quality Analysis"
subtitle: "DATA 607: Week 1 Assignment Examplar"
date: "9/1/2026"
author: "DW"
format:
  html:
    code-fold: true
    toc: true

  
editor: visual
---

# Wine Quality Analysis

## Approach

In this assignment, I selected a dataset from the UCI Machine Learning Repository that contains information about the chemical attributes of wine. The dataset contains 11 features and provides a useful opportunity to practice working with numerical data, feature selection, and classification or regression analysis.

My plan for this assignment is to load the data into R and create a label for the different wine types to use in a later classification task.

I will also perform some simple exploratory data analysis (EDA) on the datasets.

Data source:\
<https://raw.githubusercontent.com/DW8888/Wine-Quality/refs/heads/main/winequality-white.csv> <https://raw.githubusercontent.com/DW8888/Wine-Quality/refs/heads/main/winequality-red.csv>\
\
Cortez, P., Cerdeira, A., Almeida, F., Matos, T., & Reis, J. (2009). Wine Quality \[Dataset\]. UCI Machine Learning Repository. <https://doi.org/10.24432/C56S3T.>

## Research Question

Can the chemical attributes of a wine be used to classify it as red or white?\
\
